"""add report_jobs table

Revision ID: 57b892fc1044
Revises: b7d25cea795a
Create Date: 2026-08-10 19:40:04.052669

Hand-trimmed from the autogenerated diff: autogenerate also picked up a
large amount of pre-existing drift between the live schema (applied via
docs/DATABASE_SCHEMA.sql, not Alembic) and the SQLAlchemy models — renamed
check constraints, reordered indexes, and (dangerously) LangGraph's own
`checkpoint*` tables, which aren't declared in app.models at all and would
have been dropped. None of that belongs in this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '57b892fc1044'
down_revision: Union[str, Sequence[str], None] = 'b7d25cea795a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'report_jobs',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('portfolio_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Text(), server_default='ready', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("status in ('queued', 'running', 'ready', 'error')", name='ck_report_jobs_status'),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_report_jobs_user', 'report_jobs', ['user_id', 'created_at'], unique=False)


def downgrade() -> None:
    op.drop_index('idx_report_jobs_user', table_name='report_jobs')
    op.drop_table('report_jobs')
