"""initial schema

Revision ID: b7d25cea795a
Revises:
Create Date: 2026-08-09 11:31:21.512106

NOTE ON GENERATION: this migration was produced by
`alembic revision --autogenerate` run against a throwaway local SQLite DB
(no live Postgres/Supabase was available in this environment) to validate
that autogenerate sees the full model set and produces correct DDL. Two
import lines that `--autogenerate` omits by default were added by hand
after generation, since they're needed regardless of which DB the
comparison ran against:
  - `from sqlalchemy import Text` (used inside `postgresql.JSONB(astext_type=Text())`)
  - `import pgvector.sqlalchemy` (used for the `document_chunks.embedding` column)
No column types were changed from what SQLAlchemy generated — `sa.UUID()`
(a dialect-generic type since SQLAlchemy 2.0) compiles to Postgres `uuid`
correctly, and `sa.DateTime(timezone=True)` compiles to `timestamptz`.
Re-run `alembic revision --autogenerate` against a real Postgres/Supabase
database once credentials exist, to confirm no further diff is produced.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d25cea795a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions required by docs/DATABASE_SCHEMA.sql (pgvector + pgcrypto
    # for gen_random_uuid()). Not something SQLAlchemy models can express,
    # so added by hand.
    op.execute("create extension if not exists vector")
    op.execute("create extension if not exists pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor in ('user', 'agent', 'system')", name='ck_audit_log_actor'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_user', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), server_default='paper', nullable=False),
    sa.Column('status', sa.Text(), server_default='disconnected', nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("broker in ('dhan', 'angelone', 'upstox', 'fyers')", name='ck_broker_connections_broker'),
    sa.CheckConstraint("mode in ('paper', 'live')", name='ck_broker_connections_mode'),
    sa.CheckConstraint("status in ('disconnected', 'connected', 'error', 'expired')", name='ck_broker_connections_status'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_broker_conn_user', 'broker_connections', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), server_default='manual_upload', nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_type in ('filing', 'report', 'news', 'manual_upload')", name='ck_documents_source_type'),
    sa.CheckConstraint("status in ('pending', 'processing', 'ready', 'failed')", name='ck_documents_status'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_user', 'documents', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.Text(), server_default='INR', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolios_user', 'portfolios', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('risk_tolerance', sa.Text(), server_default='moderate', nullable=False),
    sa.Column('investment_horizon_years', sa.SmallInteger(), nullable=True),
    sa.Column('base_currency', sa.Text(), server_default='INR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("risk_tolerance in ('conservative', 'moderate', 'aggressive')", name='ck_profiles_risk_tolerance'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), server_default='New research session', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_sessions_user', 'agent_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    # HNSW cosine-similarity index — not expressed on the model's __table_args__
    # (see app/models/document_chunk.py) because SQLAlchemy's generic Index()
    # construct doesn't have first-class HNSW op-class support across every
    # version we might run against; added directly here instead.
    op.execute(
        "CREATE INDEX idx_chunks_embedding ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('broker_connection_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), server_default='NSE', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('asset_class', sa.Text(), server_default='equity', nullable=False),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='INR', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("asset_class in ('equity', 'etf', 'mutual_fund', 'bond', 'cash', 'commodity', 'crypto')", name='ck_holdings_asset_class'),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', 'exchange', name='uq_holdings_portfolio_symbol')
    )
    op.create_index('idx_holdings_portfolio', 'holdings', ['portfolio_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('volatility_annual', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('concentration_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_portfolio', 'risk_assessments', ['portfolio_id', 'computed_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), server_default='NSE', nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('broker_order_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("side in ('buy', 'sell')", name='ck_transactions_side'),
    sa.CheckConstraint("source in ('broker_sync', 'manual', 'agent_trade')", name='ck_transactions_source'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_portfolio', 'transactions', ['portfolio_id', 'executed_at'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), server_default='NSE', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', 'exchange', name='uq_watchlist_symbol')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant', 'tool', 'system')", name='ck_agent_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_messages_session', 'agent_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('trade_approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_connection_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), server_default='NSE', nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_type', sa.Text(), server_default='market', nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('requested_by', sa.Text(), server_default='agent', nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('risk_checks', postgresql.JSONB(astext_type=Text()), server_default='{}', nullable=False),
    sa.Column('broker_order_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("order_type in ('market', 'limit')", name='ck_trade_approvals_order_type'),
    sa.CheckConstraint("requested_by in ('agent', 'user')", name='ck_trade_approvals_requested_by'),
    sa.CheckConstraint("side in ('buy', 'sell')", name='ck_trade_approvals_side'),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected', 'expired', 'executed', 'failed')", name='ck_trade_approvals_status'),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_approvals_user', 'trade_approvals', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###

    # Row Level Security — mirrors docs/DATABASE_SCHEMA.sql verbatim. Not
    # something an ORM model expresses; added by hand for parity with the
    # documented schema (RLS is the source of truth for row-level access;
    # the backend additionally checks ownership in the service layer).
    op.execute("alter table public.profiles            enable row level security")
    op.execute("alter table public.portfolios          enable row level security")
    op.execute("alter table public.broker_connections  enable row level security")
    op.execute("alter table public.holdings            enable row level security")
    op.execute("alter table public.transactions         enable row level security")
    op.execute("alter table public.watchlists           enable row level security")
    op.execute("alter table public.watchlist_items      enable row level security")
    op.execute("alter table public.documents            enable row level security")
    op.execute("alter table public.agent_sessions       enable row level security")
    op.execute("alter table public.agent_messages       enable row level security")
    op.execute("alter table public.trade_approvals      enable row level security")
    op.execute("alter table public.risk_assessments     enable row level security")
    op.execute("alter table public.audit_log            enable row level security")
    op.execute("alter table public.document_chunks      enable row level security")

    op.execute('create policy "own profile" on public.profiles for all using (user_id = auth.uid())')
    op.execute('create policy "own portfolios" on public.portfolios for all using (user_id = auth.uid())')
    op.execute('create policy "own broker connections" on public.broker_connections for all using (user_id = auth.uid())')
    op.execute(
        'create policy "own holdings" on public.holdings for all using '
        "(portfolio_id in (select id from public.portfolios where user_id = auth.uid()))"
    )
    op.execute(
        'create policy "own transactions" on public.transactions for all using '
        "(portfolio_id in (select id from public.portfolios where user_id = auth.uid()))"
    )
    op.execute('create policy "own watchlists" on public.watchlists for all using (user_id = auth.uid())')
    op.execute(
        'create policy "own watchlist items" on public.watchlist_items for all using '
        "(watchlist_id in (select id from public.watchlists where user_id = auth.uid()))"
    )
    op.execute(
        'create policy "own or shared documents" on public.documents for select using '
        "(user_id = auth.uid() or user_id is null)"
    )
    op.execute(
        'create policy "manage own documents" on public.documents for insert with check (user_id = auth.uid())'
    )
    op.execute('create policy "update own documents" on public.documents for update using (user_id = auth.uid())')
    op.execute('create policy "delete own documents" on public.documents for delete using (user_id = auth.uid())')
    op.execute('create policy "own agent sessions" on public.agent_sessions for all using (user_id = auth.uid())')
    op.execute(
        'create policy "own agent messages" on public.agent_messages for all using '
        "(session_id in (select id from public.agent_sessions where user_id = auth.uid()))"
    )
    op.execute('create policy "own trade approvals" on public.trade_approvals for all using (user_id = auth.uid())')
    op.execute(
        'create policy "own risk assessments" on public.risk_assessments for all using '
        "(portfolio_id in (select id from public.portfolios where user_id = auth.uid()))"
    )
    op.execute('create policy "own audit log" on public.audit_log for select using (user_id = auth.uid())')
    op.execute(
        'create policy "chunks of visible documents" on public.document_chunks for select using '
        "(document_id in (select id from public.documents where user_id = auth.uid() or user_id is null))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Policies/RLS are dropped implicitly when their tables are dropped
    # below; Postgres removes policies and index defs along with the table.
    # Extensions are intentionally left installed (other objects in the DB
    # may depend on them) — drop manually if truly no longer needed.
    op.execute("DROP INDEX IF EXISTS idx_chunks_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_approvals_user', table_name='trade_approvals')
    op.drop_table('trade_approvals')
    op.drop_index('idx_agent_messages_session', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_table('watchlist_items')
    op.drop_index('idx_transactions_portfolio', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_risk_portfolio', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('idx_holdings_portfolio', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('idx_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_agent_sessions_user', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('watchlists')
    op.drop_table('profiles')
    op.drop_index('idx_portfolios_user', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('idx_documents_user', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_broker_conn_user', table_name='broker_connections')
    op.drop_table('broker_connections')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
